### PR TITLE
EF Core repositories extended for searches and creations in database

### PR DESCRIPTION
**Pull request by JakobArnfred**

### CODE REVIEW

**Review by SnowyPeax — CHANGES_REQUESTED** [review]
You've certainly been productive - good job overall! Please refer to the list below for some changes that should be effectuated according to me. You can answer in this thread if any seem misplaced given the task.

- [ ] Handle warnings
- [ ] Remove unnecessary comments (and comment on any necessary ones - should there be any - what their purpose is)
- [x] Introduce unit tests for AuthorRepository.cs
- [ ] Handle the case when the author does not exist  (see image) and add unit tests for this

image

**Review by SnowyPeax — CHANGES_REQUESTED** [review]
Good job with the arrange, act, assert formula! Concept-wise the tests appear sound.

Now for some feedback:

Please refer back to my previous comment as it seems not all advice was heeded or even considered (you'll have to correct me should I be mistaken on that)

In addition the naming of the tests does not comply with best practices (see image) and it strikes me as somewhat random that get author by email is a test when get author by name is not. I see that it is because it is used in the integration test of CreateNewAuthor_Values, however in case this one should fail it would be harder to identify the point of failure and it is not evident for someone not somewhat intimately familier with the code that this should be the reasoning for it not existing (which is aggravated by the naming).

Excuse my rambling. Good effort and tak for i dag!


image

**Comment by JakobArnfred** [comment]
Thanks for the different feedback to the branch. 
The "Handle the case when the author does not exist (see image) and add unit tests for this" has been discussed in the group. This will need to be implemented later, when the createCheep(...)-method is called somewhere in the code-implementation. The reason is that the two repositories should not refer directly to eachother

**Review by LavenderPlush — APPROVED** [review]
These changes introduce readable code and elegant solutions to warnings. The tests might be somewhat lacking, but they still provide an acceptable coverage.
The functions added to repository also seem to follow CQS.
The GetHumanReadableId is currently public, but should be private if not used elsewhere.

**Pull request merged**
