### PR TITLE
Feature like cheeps

### PR DESCRIPTION
**Pull request by LavenderPlush**
This branch introduces a restriction on deletion of authors.
The "forget me" feature has been updated to account for this change.

### CODE REVIEW

**Review by Philipnah — CHANGES_REQUESTED** [review]
Just by looking at the code (I haven't run any tests nor the program on this branch), I would request to change the async methods of the CheepRepository to make them synchronous since EF Core does not support any parallel operations.

"Entity Framework Core does not support multiple parallel operations being run on the same DbContext instance. This includes both parallel execution of async queries and any explicit concurrent use from multiple threads. Therefore, always await async calls immediately, or use separate DbContext instances for operations that execute in parallel." from https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues

**Review by SnowyPeax — CHANGES_REQUESTED** [review]
Note that I have yet to really read the code in details.

Overall the changes looks good.
I have observed the following bugs / things that don't comply with requirements:

 - You cannot send cheeps after liking ( see image 1 )
 - When liking other's cheeps they do not show up on the about me page
 - Likes do not always seem to register (for example after pushing forget me)
 - The like button is bugged on personal timelines (see image 3 + 4)
 - (more of an inconvenience) liking sends you back to page 1

These are just the ones that were apparent right away. I know we want extra features to make the program seem complete but I believe introducing bugged features will prove more of a detriment. I hope you agree with this sentiment and that we can sort this out as the feature is otherwise nice and can be used as a platform for others. Pardon my rant. Have a good weekend :)

image

image

image

image

**Comment by Philipnah** [comment]
I too, seem to have found bugs in this new feature. At least Johan and I seem to both have these bugs on our machines. 🐞

**Review by Philipnah — APPROVED** [review]
After a code review, this code seems nice. Great work! 🎉

**Pull request merged**
