### PR TITLE
Establish DTOs

### PR DESCRIPTION
**Pull request by LavenderPlush**

### CODE REVIEW

**Comment by SnowyPeax** [comment]
Looks good overall. The only change that I would suggest is avoiding the use of DateTime (see photo for details)

image

**Comment by Philipnah** [comment]
I'm not sure, but shouldn't the DTOs only contain data that we show to the user? If so, then we wouldn't want to include any IDs, since they are never shown to the user.

Perhaps I would also change the name of "CreatedAt" to "TimeStamp" just to keep the naming consistant. :)

**Review by Philipnah — CHANGES_REQUESTED** [review]
I'm not sure, but shouldn't the DTOs only contain data that we show to the user? If so, then we wouldn't want to include any IDs, since they are never shown to the user.

Perhaps I would also change the name of "CreatedAt" to "TimeStamp" just to keep the naming consistant. :)

**Review by Philipnah — CHANGES_REQUESTED** [review]
Looks good! Should the email really be shown to the user? I know Rasmus mentioned it, but perhaps it is not need for our program.
Maybe the properties should be "required"?

**Comment by LavenderPlush** [comment]
> Looks good! Should the email really be shown to the user? I know Rasmus mentioned it, but perhaps it is not need for our program. Maybe the properties should be "required"?

Keep in mind DTOs are simple objects and should avoid validation logic as this blurs the line between data representation and business logic.
The DTO contains the e-mail of the user for users being logged in. Remember that the site uses server-side rendering to produce the frontend and therefore the logic regarding whether to show the e-mail or not is done in the templating.

**Pull request merged**
